http://{default}/:
  type: redirect
  redirects:
    expires: -1s
    paths: {}
  to: https://{default}/
http://www.{default}/:
  type: redirect
  redirects:
    expires: -1s
    paths: {}
  to: https://{default}/
https://www.{default}/:
  type: redirect
  redirects:
    expires: -1s
    paths: {}
  to: https://{default}/
https://{default}/:
  type: upstream
  redirects:
    expires: -1s
    paths:
      '/.*':
        to: 'https://www.ilr.cornell.edu/programs/professional-education/senior-leader-courses'
        regexp: true
  cache:
    enabled: true
    default_ttl: 900
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: true
  upstream: app:http
